name: Terrateam
on:
  workflow_dispatch:
    inputs:
      work-token:
        description: 'Work token for run'
        required: true
      api-base-url:
        description: 'Base URL to API'
        required: true
        default: 'https://app.terrateam.io'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created

jobs:
  terrateam:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: read
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    name: Terrateam Action
    steps:
      - uses: actions/checkout@v4
      - uses: terrateamio/action@v1
        with:
          work-token: '${{ github.event.inputs.work-token }}'
          api-base-url: '${{ github.event.inputs.api-base-url }}'
        env:
          POC_ARM_CLIENT_ID: ${{ secrets.POC_ARM_CLIENT_ID }}
          POC_ARM_CLIENT_SECRET: ${{ secrets.POC_ARM_CLIENT_SECRET }}
          POC_ARM_SUBSCRIPTION_ID: ${{ secrets.POC_ARM_SUBSCRIPTION_ID }}
          POC_ARM_TENANT_ID: ${{ secrets.POC_ARM_TENANT_ID }}
          POC_POSTGRESQL_ADMIN_PASSWORD: ${{ secrets.POC_POSTGRESQL_ADMIN_PASSWORD }}
